<?php

namespace ContainerUxxjlii;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QMp2t6CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QMp2t6C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QMp2t6C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CompetencesController::add_competences' => ['privates', '.service_locator.I9akgJ8', 'get_ServiceLocator_I9akgJ8Service', true],
            'App\\Controller\\GroupTagController::addGropeTag' => ['privates', '.service_locator.WzYPJck', 'get_ServiceLocator_WzYPJckService', true],
            'App\\Controller\\GroupTagController::edit_tag' => ['privates', '.service_locator.eykHcDB', 'get_ServiceLocator_EykHcDBService', true],
            'App\\Controller\\GroupeCompetenceController::addGroupeCompetences' => ['privates', '.service_locator.kcdejuf', 'get_ServiceLocator_KcdejufService', true],
            'App\\Controller\\GroupeCompetenceController::edit_groupe_competence' => ['privates', '.service_locator.pAlD7t2', 'get_ServiceLocator_PAlD7t2Service', true],
            'App\\Controller\\GroupeController::edit_groupe' => ['privates', '.service_locator.NDmk86f', 'get_ServiceLocator_NDmk86fService', true],
            'App\\Controller\\GroupeController::removeApprenantFromGroup' => ['privates', '.service_locator.NDmk86f', 'get_ServiceLocator_NDmk86fService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CompetencesController:add_competences' => ['privates', '.service_locator.I9akgJ8', 'get_ServiceLocator_I9akgJ8Service', true],
            'App\\Controller\\GroupTagController:addGropeTag' => ['privates', '.service_locator.WzYPJck', 'get_ServiceLocator_WzYPJckService', true],
            'App\\Controller\\GroupTagController:edit_tag' => ['privates', '.service_locator.eykHcDB', 'get_ServiceLocator_EykHcDBService', true],
            'App\\Controller\\GroupeCompetenceController:addGroupeCompetences' => ['privates', '.service_locator.kcdejuf', 'get_ServiceLocator_KcdejufService', true],
            'App\\Controller\\GroupeCompetenceController:edit_groupe_competence' => ['privates', '.service_locator.pAlD7t2', 'get_ServiceLocator_PAlD7t2Service', true],
            'App\\Controller\\GroupeController:edit_groupe' => ['privates', '.service_locator.NDmk86f', 'get_ServiceLocator_NDmk86fService', true],
            'App\\Controller\\GroupeController:removeApprenantFromGroup' => ['privates', '.service_locator.NDmk86f', 'get_ServiceLocator_NDmk86fService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CompetencesController::add_competences' => '?',
            'App\\Controller\\GroupTagController::addGropeTag' => '?',
            'App\\Controller\\GroupTagController::edit_tag' => '?',
            'App\\Controller\\GroupeCompetenceController::addGroupeCompetences' => '?',
            'App\\Controller\\GroupeCompetenceController::edit_groupe_competence' => '?',
            'App\\Controller\\GroupeController::edit_groupe' => '?',
            'App\\Controller\\GroupeController::removeApprenantFromGroup' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CompetencesController:add_competences' => '?',
            'App\\Controller\\GroupTagController:addGropeTag' => '?',
            'App\\Controller\\GroupTagController:edit_tag' => '?',
            'App\\Controller\\GroupeCompetenceController:addGroupeCompetences' => '?',
            'App\\Controller\\GroupeCompetenceController:edit_groupe_competence' => '?',
            'App\\Controller\\GroupeController:edit_groupe' => '?',
            'App\\Controller\\GroupeController:removeApprenantFromGroup' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
