<?php

namespace ContainerUxxjlii;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EykHcDBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eykHcDB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eykHcDB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'grpTag_Repo' => ['privates', 'App\\Repository\\GroupTagRepository', 'getGroupTagRepositoryService', true],
            'tagRepo' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'grpTag_Repo' => 'App\\Repository\\GroupTagRepository',
            'tagRepo' => 'App\\Repository\\TagRepository',
        ]);
    }
}
