<?php

namespace ContainerUxxjlii;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormateurPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\FormateurPersister' shared autowired service.
     *
     * @return \App\DataPersister\FormateurPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataPersister/FormateurPersister.php';

        return $container->privates['App\\DataPersister\\FormateurPersister'] = new \App\DataPersister\FormateurPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
