<?php

namespace ContainerS9dmJ8b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Doctrine_Listener_HttpCache_PurgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.doctrine.listener.http_cache.purge' shared service.
     *
     * @return \ApiPlatform\Core\Bridge\Doctrine\EventListener\PurgeHttpCacheListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/HttpCache/PurgerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/HttpCache/VarnishPurger.php';

        return $container->privates['api_platform.doctrine.listener.http_cache.purge'] = new \ApiPlatform\Core\Bridge\Doctrine\EventListener\PurgeHttpCacheListener(new \ApiPlatform\Core\HttpCache\VarnishPurger([]), ($container->privates['api_platform.iri_converter'] ?? $container->getApiPlatform_IriConverterService()), ($container->privates['api_platform.resource_class_resolver'] ?? $container->getApiPlatform_ResourceClassResolverService()));
    }
}
