<?php

namespace Container3U7goBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NDmk86fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NDmk86f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NDmk86f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apprenant_repo' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'groupe_repository' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
        ], [
            'apprenant_repo' => 'App\\Repository\\ApprenantRepository',
            'groupe_repository' => 'App\\Repository\\GroupeRepository',
        ]);
    }
}
