<?php

namespace Container3U7goBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupTagControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GroupTagController' shared autowired service.
     *
     * @return \App\Controller\GroupTagController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GroupTagController.php';

        $container->services['App\\Controller\\GroupTagController'] = $instance = new \App\Controller\GroupTagController(($container->services['serializer'] ?? $container->getSerializerService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['validator'] ?? $container->getValidatorService()));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\GroupTagController', $container));

        return $instance;
    }
}
