<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHDTQbXx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHDTQbXx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHDTQbXx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHDTQbXx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHDTQbXx\App_KernelProdContainer([
    'container.build_hash' => 'HDTQbXx',
    'container.build_id' => '821d92ee',
    'container.build_time' => 1605537766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHDTQbXx');
