<?php

namespace ContainerDStWiHn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VQm2ZWqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VQm2ZWq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VQm2ZWq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CompetencesController::add_competences' => ['privates', '.service_locator.I9akgJ8', 'get_ServiceLocator_I9akgJ8Service', true],
            'App\\Controller\\GroupeCompetenceController::addGroupeCompetences' => ['privates', '.service_locator.kcdejuf', 'get_ServiceLocator_KcdejufService', true],
            'App\\Controller\\GroupeCompetenceController::edit_groupe_competence' => ['privates', '.service_locator.pAlD7t2', 'get_ServiceLocator_PAlD7t2Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CompetencesController:add_competences' => ['privates', '.service_locator.I9akgJ8', 'get_ServiceLocator_I9akgJ8Service', true],
            'App\\Controller\\GroupeCompetenceController:addGroupeCompetences' => ['privates', '.service_locator.kcdejuf', 'get_ServiceLocator_KcdejufService', true],
            'App\\Controller\\GroupeCompetenceController:edit_groupe_competence' => ['privates', '.service_locator.pAlD7t2', 'get_ServiceLocator_PAlD7t2Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CompetencesController::add_competences' => '?',
            'App\\Controller\\GroupeCompetenceController::addGroupeCompetences' => '?',
            'App\\Controller\\GroupeCompetenceController::edit_groupe_competence' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CompetencesController:add_competences' => '?',
            'App\\Controller\\GroupeCompetenceController:addGroupeCompetences' => '?',
            'App\\Controller\\GroupeCompetenceController:edit_groupe_competence' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
