<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDaiWVqy\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDaiWVqy/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDaiWVqy.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDaiWVqy\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDaiWVqy\App_KernelTestDebugContainer([
    'container.build_hash' => 'DaiWVqy',
    'container.build_id' => '6683b859',
    'container.build_time' => 1606127029,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDaiWVqy');
