<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI26qWpE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI26qWpE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI26qWpE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI26qWpE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI26qWpE\App_KernelDevDebugContainer([
    'container.build_hash' => 'I26qWpE',
    'container.build_id' => 'f2a9840c',
    'container.build_time' => 1605533079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI26qWpE');
