<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5mPNI9l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5mPNI9l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5mPNI9l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5mPNI9l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5mPNI9l\App_KernelDevDebugContainer([
    'container.build_hash' => '5mPNI9l',
    'container.build_id' => '6352b660',
    'container.build_time' => 1605561341,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5mPNI9l');
