<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOqGhfMs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOqGhfMs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOqGhfMs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOqGhfMs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOqGhfMs\App_KernelDevDebugContainer([
    'container.build_hash' => 'OqGhfMs',
    'container.build_id' => 'b9a67af3',
    'container.build_time' => 1605618801,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOqGhfMs');
